name: Build docker images and push do registry

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push service
        uses: docker/build-push-action@v4
        with:
          context: ./service
          file: ./service/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/l0-service:latest
      - name: Build and push postgres
        uses: docker/build-push-action@v4
        with:
          context: ./postgres
          file: ./postgres/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/l0-postgres:latest
      - name: Build and push ui (order-display)
        uses: docker/build-push-action@v4
        with:
          context: ./order-display
          file: ./order-display/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/l0-order-display:latest

  test-compose:
    name: Test `docker-compose up`
    needs: build-and-push-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Perform docker-compose up
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: ./docker-compose.yml

  send-tg-notification:
    name: Send telegram notification
    runs-on: ubuntu-latest
    steps:
      - name: get repos name
        env:
          REPO_NAME: ${{ github.repository }}
        id: repo_name
        run: echo "::set-output name=fragment::${REPO_NAME##*/}"
      - uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_TO}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          format: markdown
          message: |
            #${{steps.repo_name.outputs.fragment}} #${{github.actor}}
            Repository: ```${{github.repository}}```
            ```${{github.actor}}``` pushed to branch `main`:
            Commit message: ```${{github.event.head_commit.message}}```
            https://github.com/${{ github.repository }}/commit/${{github.sha}}

