name: Build docker images and push do registry

on:
  push:
    branches:
      - "main"

jobs:
  build-and-push-service-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./service
          file: ./service/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/l0:latest
  
  test-compose:
    name: Test `docker-compose up`
    needs: build-and-push-service-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Perform docker-compose up
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: ./docker-compose.yml