name: Telegram notification

on:
  push:
  workflow_dispatch:

jobs:
  send_notification:
    name: Send notification
    runs-on: ubuntu-latest
    steps:
      - name: get repos name
        env:
          REPO_NAME: ${{ github.repository }}
        id: repo_name
        run: echo "::set-output name=fragment::${REPO_NAME##*/}"
      - name: construct message
        id: message_text
        run: echo "::set-output name=message::${#${{steps.repo_name.outputs.fragment}} #${{github.actor}}\nRepository: ```${{github.repository}}```\n```${{github.actor}}``` pushed to branch `main`:\nCommit message: ```${{github.event.head_commit.message}}```\nhttps://github.com/${{ github.repository }}/commit/${{github.sha}}}"
      - name: send
        run: |
          curl -w "\n" -d '{"chat_id": "${{secrets.TELEGRAM_TO}}", "text": "${{steps.message_text.outputs.message}}"}' https://api.telegram.org/bot${{secrets.TELEGRAM_TOKEN}}/sendMessage