name: Telegram notification

on:
  push:
  workflow_dispatch:

jobs:
  send_notification:
    name: Send notification
    runs-on: ubuntu-latest
    steps:
      - name: get repos name
        env:
          REPO_NAME: ${{ github.repository }}
        id: repo_name
        run: echo "::set-output name=fragment::${REPO_NAME##*/}"
        
      - name: construct message
        id: message_text
        # run: echo "::set-output name=message::${\n\n}"
        run: |
          echo 'text=#${{steps.repo_name.outputs.fragment}} #${{github.actor}}
          Repository: ***${{github.repository}}***
          ***${{github.actor}}*** pushed to branch `main`
          Commit message: ***${{github.event.head_commit.message}}***
          https://github.com/${{ github.repository }}/commit/${{github.sha}}' >> $GITHUB_OUTPUT
        #  echo '#${{steps.repo_name.outputs.fragment}} #${{github.actor}}
        #  Repository: ***${{github.repository}}***
        #  ***${{github.actor}}*** pushed to branch `main`
        #  Commit message: ***${{github.event.head_commit.message}}***
        #  https://github.com/${{ github.repository }}/commit/${{github.sha}}' >> $GITHUB_OUTPUT
          
      - name: send
        run: |
          curl -w "\n" -d '{"chat_id": ${{secrets.TELEGRAM_TO}}, "text": "${{steps.message_text.outputs.text}}"}' \
          https://api.telegram.org/bot${{secrets.TELEGRAM_TOKEN}}/sendMessage \
          -H 'Content-Type: application/json'
