name: Telegram notification

on:
  push:
  workflow_dispatch:

jobs:
  send_notification-with-custom-action:
    name: Custom tg notification
    runs-on: ubuntu-latest
    steps:
      - name: send
        uses: neoetheilred/tgnotification@main
        with:
          telegram_token: ${{secrets.TELEGRAM_TOKEN}}
          chat_id: ${{secrets.TELEGRAM_TO}}
          formatting: MarkdownV2
          message: |
            \\\\#${{steps.repo_name.outputs.fragment}} \\\\#${{github.actor}}
            Repository: \`${{github.repository}}\`
            `${{github.actor}}` pushed to branch `main`
            Commit message: `${{github.event.head_commit.message}}`
            [Commit details](https://github.com/${{ github.repository }}/commit/${{github.sha}})
          
  send_notification:
    name: Send notification
    runs-on: ubuntu-latest
    steps:
      - name: get repos name
        env:
          REPO_NAME: ${{ github.repository }}
        id: repo_name
        run: echo "::set-output name=fragment::${REPO_NAME##*/}"
        
      - name: construct message
        id: message_text
        # run: echo "::set-output name=message::${\n\n}"
        run: |
          MESSAGE_TEXT=$(cat<<EOF
          \\\\#${{steps.repo_name.outputs.fragment}} \\\\#${{github.actor}}
          Repository: \`${{github.repository}}\`
          \`${{github.actor}}\` pushed to branch \`main\`
          Commit message: \`${{github.event.head_commit.message}}\`
          [Commit details](https://github.com/${{ github.repository }}/commit/${{github.sha}})
          EOF
          )
          echo "MESSAGE_TEXT<<EOF" >> $GITHUB_ENV
          echo "$MESSAGE_TEXT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        #  echo 'text="#${{steps.repo_name.outputs.fragment}} #${{github.actor}}
        #  Repository: ***${{github.repository}}***
        #  ***${{github.actor}}*** pushed to branch `main`
        #  Commit message: ***${{github.event.head_commit.message}}***
        #  https://github.com/${{ github.repository }}/commit/${{github.sha}}"' >> $GITHUB_OUTPUT
        #  echo '#${{steps.repo_name.outputs.fragment}} #${{github.actor}}
        #  Repository: ***${{github.repository}}***
        #  ***${{github.actor}}*** pushed to branch `main`
        #  Commit message: ***${{github.event.head_commit.message}}***
        #  https://github.com/${{ github.repository }}/commit/${{github.sha}}' >> $GITHUB_OUTPUT
          
      - name: send
        run: |
          curl -w "\n" -d '{"chat_id": ${{secrets.TELEGRAM_TO}}, "text": "${{env.MESSAGE_TEXT}}", "parse_mode": "MarkdownV2"}' \
          https://api.telegram.org/bot${{secrets.TELEGRAM_TOKEN}}/sendMessage \
          -H 'Content-Type: application/json'
